"""empty message

Revision ID: f576335648c8
Revises: 17e0db018227
Create Date: 2021-02-28 10:22:07.537105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f576335648c8'
down_revision = '17e0db018227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'facebook_link')
    # ### end Alembic commands ###
